### ISSUE TITLE
~/.ssh/comfy_vm_key" failed: No such file or directory

### ISSUE THREAD

**Issue by LukeOvermind** [karaposu/comfyui-on-cloud#1]
Hi once again

I installed as suggest by you on Reddit the Google Cloud SDK Shell  https://cloud.google.com/sdk/docs/install#windows. 

I did not do step 5 seeing that I installed it as above.

When running  Google Cloud SDK Shell  it  start at the following path C:\Program Files (x86)\Google\Cloud SDK>

Is this the  correct path??? 

 
I had to install wget and downloaded https://github.com/PowerShell/Win32-OpenSSH/releases and copied the extracted folder to C:\Program Files (x86)\Google\Cloud SDK> I was able to do run

gcloud auth login
gcloud init

with no issue 

but with ssh-keygen -t rsa -b 2048 -C "comfy_vm_key" -f ~/.ssh/comfy_vm_key I get 

~/.ssh/comfy_vm_key" failed: No such file or directory

Trying to make a directory  like below I get 

C:\Program Files (x86)\Google\Cloud SDK>mkdir ~/.ssh
The syntax of the command is incorrect.

Please help!

**Comment by karaposu** [comment]
got you, i will update the codes for windows users asap

**Comment by karaposu** [comment]
fix is pushed
