### ISSUE TITLE
Installing Ollama

### ISSUE THREAD

**Issue by LukeOvermind** [karaposu/comfyui-on-cloud#2]
Hi there! 

Is there a way of installing Ollama LLM through the Google Cloud SSH terminal ?

https://github.com/ollama/ollama?tab=readme-ov-file

How would one go about it?

**Comment by karaposu** [comment]
@LukeOvermind yeah,  just ssh into your your machine and follow usual instructions to install Ollama

**Comment by LukeOvermind** [comment]
Thanks got it working!
